const $ = (selector) => document.querySelector(selector);
const STORAGE_KEY = 'ccaf-practice-v3';
const DEFAULT_STATE = { answers: {}, flagged: {} };
let state = loadState();
let questions = [];
let queue = [];
let index = 0;
let drag = null;
const filters = { mode: 'study', domain: 'all', difficulty: 'all', section: 'all' };
function loadState(){try{return {...DEFAULT_STATE,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(DEFAULT_STATE)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function answerFor(q){return state.answers[q.id]}
function sectionOf(q){return q.section || q.topic || 'General'}
async function loadQuestions(){const response=await fetch('./questions.json?v=3',{cache:'no-store'});if(!response.ok)throw new Error(`Question bank failed to load (${response.status})`);const data=await response.json();if(!Array.isArray(data)||data.length!==200)throw new Error(`Expected 200 questions, received ${Array.isArray(data)?data.length:'invalid data'}`);return data}
function populateFilters(){const domains=[...new Set(questions.map(q=>q.domain))].sort();const sections=[...new Set(questions.map(sectionOf))].sort();for(const value of domains){const option=document.createElement('option');option.value=value;option.textContent=value;$('#domainFilter').append(option)}for(const value of sections){const option=document.createElement('option');option.value=value;option.textContent=value;$('#sectionFilter').append(option)}}
function matchesFilters(q){const answered=!!answerFor(q),flagged=!!state.flagged[q.id];if(filters.domain!=='all'&&q.domain!==filters.domain)return false;if(filters.difficulty!=='all'&&q.difficulty!==filters.difficulty)return false;if(filters.section!=='all'&&sectionOf(q)!==filters.section)return false;if(filters.mode==='study'&&answered)return false;if(filters.mode==='review'&&!answered)return false;if(filters.mode==='flagged'&&!flagged)return false;return true}
function buildQueue(){queue=questions.filter(matchesFilters);index=Math.min(index,Math.max(queue.length-1,0));render()}
function render(){const q=queue[index];$('#emptyState').classList.toggle('hidden',!!q);$('#card').classList.toggle('hidden',!q);$('#laterBtn').disabled=!q;$('#submitBtn').disabled=!q;$('#retakeFlaggedBtn').classList.toggle('hidden',filters.mode!=='flagged'||!queue.length);if(!q){updateMetrics();return}const saved=answerFor(q);$('#domainChip').textContent=q.domain;$('#difficultyChip').textContent=q.difficulty;$('#sourceChip').textContent=q.source_tag||q.source||'blueprint-derived';$('#sectionName').textContent=sectionOf(q);$('#questionCounter').textContent=`${q.id} · ${index+1} / ${queue.length}`;$('#questionText').textContent=q.question||q.stem;const options=Array.isArray(q.options)?Object.fromEntries(q.options.map(o=>[o.id,o.text])):q.options;const correct=q.correct_answer||q.answer;const fieldset=$('#optionsFieldset');fieldset.innerHTML='<legend class="sr-only">Choose one answer</legend>';for(const [key,text] of Object.entries(options)){const label=document.createElement('label');label.className='option';if(saved&&key===correct)label.classList.add('correct');if(saved&&saved.choice===key&&key!==correct)label.classList.add('wrong');const input=document.createElement('input');input.type='radio';input.name='answer';input.value=key;input.checked=!!saved&&saved.choice===key;input.disabled=!!saved;const letter=document.createElement('span');letter.className='letter';letter.textContent=key;const body=document.createElement('span');body.className='option-text';body.textContent=text;label.append(input,letter,body);fieldset.append(label)}const feedback=$('#feedback');if(saved){const ok=saved.choice===correct;feedback.className=`feedback ${ok?'correct':'wrong'}`;feedback.innerHTML=`<strong>${ok?'Correct':'Not quite'} · Answer ${correct}</strong><span>${q.explanation||q.rationale||''}</span>`;$('#submitBtn').textContent=index<queue.length-1?'Next →':'Finish →'}else{feedback.className='feedback hidden';feedback.textContent='';$('#submitBtn').textContent='Submit →'}updateMetrics()}
function updateMetrics(){const scope=questions.filter(q=>(filters.domain==='all'||q.domain===filters.domain)&&(filters.difficulty==='all'||q.difficulty===filters.difficulty)&&(filters.section==='all'||sectionOf(q)===filters.section));const answered=scope.filter(q=>answerFor(q));const correct=answered.filter(q=>{const a=answerFor(q);return a.choice===(q.correct_answer||q.answer)}).length;const flagged=scope.filter(q=>state.flagged[q.id]).length;$('#answeredMetric').textContent=answered.length;$('#flaggedMetric').textContent=flagged;$('#remainingMetric').textContent=Math.max(scope.length-answered.length,0);$('#scoreMetric').textContent=answered.length?`${Math.round(correct/answered.length*100)}%`:'0%';$('#progressBar').style.width=scope.length?`${answered.length/scope.length*100}%`:'0%';$('#progressText').textContent=`${answered.length} of ${scope.length} answered in this selection`}
function submit(){const q=queue[index];if(!q)return;if(answerFor(q)){advance();return}const chosen=document.querySelector('input[name="answer"]:checked')?.value;if(!chosen){showTemporary('Select an option first.');return}state.answers[q.id]={choice:chosen,ts:Date.now()};delete state.flagged[q.id];saveState();render()}
function flagLater(){const q=queue[index];if(!q)return;state.flagged[q.id]=true;saveState();queue.splice(index,1);if(index>=queue.length)index=Math.max(0,queue.length-1);render()}
function advance(){if(index<queue.length-1){index++;render()}else{buildQueue()}}
function showTemporary(message){const el=$('#feedback');el.className='feedback wrong';el.textContent=message;setTimeout(()=>{if(queue[index]&&!answerFor(queue[index]))el.className='feedback hidden'},1000)}
function retakeFlagged(){const ids=questions.filter(q=>state.flagged[q.id]).map(q=>q.id);for(const id of ids)delete state.answers[id];saveState();index=0;buildQueue()}
$('#submitBtn').addEventListener('click',submit);$('#laterBtn').addEventListener('click',flagLater);$('#retakeFlaggedBtn').addEventListener('click',retakeFlagged);$('#resetAllBtn').addEventListener('click',()=>{if(confirm('Reset every answer and Solve Later flag?')){state=structuredClone(DEFAULT_STATE);saveState();index=0;buildQueue()}});for(const [id,key] of [['modeFilter','mode'],['domainFilter','domain'],['difficultyFilter','difficulty'],['sectionFilter','section']]){$(`#${id}`).addEventListener('change',e=>{filters[key]=e.target.value;index=0;buildQueue()})}document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')submit();if(e.key==='ArrowLeft')flagLater()});const card=$('#card');card.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;drag={x:e.clientX,y:e.clientY,pointerId:e.pointerId};card.setPointerCapture?.(e.pointerId);card.classList.add('dragging')});card.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)>Math.abs(dy))card.style.transform=`translateX(${dx*.42}px) rotate(${dx*.011}deg)`});function finishDrag(e){if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag=null;card.classList.remove('dragging');card.style.transform='';if(Math.abs(dx)>80&&Math.abs(dx)>Math.abs(dy)*1.2){dx>0?submit():flagLater()}}card.addEventListener('pointerup',finishDrag);card.addEventListener('pointercancel',()=>{drag=null;card.classList.remove('dragging');card.style.transform=''});
try{questions=await loadQuestions();populateFilters();buildQueue();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(error){console.error(error);$('#card').classList.add('hidden');$('#emptyState').classList.remove('hidden');$('#emptyState').innerHTML=`<h2>Question bank could not load</h2><p>${error.message}</p><p>Refresh once the latest deployment is available.</p>`}
